feature/BCCAT-192 templates for maven pom generation
IntellectEU/catalyst-bootstrap pull request #29
Opened 2018-07-31 14:18 UTC by taras-shvyryd-intellecteu

The feature was needed to add the soap use case, so it`s configured for this but use case isn`t present in this branch. To generate an example project with added plugins, change 'soapconnector' key in PluginBinding class to other use case id and chose this use case in UI while generating.

2018-07-31 16:55 UTC, oborovyk approved these changes

2018-08-01 08:18 UTC, Igor-Ivaniuk requested changes

2018-08-01 08:18 UTC, Igor-Ivaniuk commented on catalyst-generator/src/main/java/com/intellecteu/catalyst/util/PluginBinding.java
> + * Accordance between use cases and plugins needed
This should be a part of YML config entry of /catalyst-service/src/main/resources/application.yml, alongside with other use-cases configuration. You can add your custom **mavenPlugins** section to describe plugin dependencies

2018-08-01 08:18 UTC, Igor-Ivaniuk commented on catalyst-generator/src/main/java/com/intellecteu/catalyst/generator/ProjectGenerator.java
> +import java.util.*;
Please reformat using GoogleStyle to avoid star imports

2018-08-01 08:18 UTC, Igor-Ivaniuk commented on catalyst-generator/src/main/java/com/intellecteu/catalyst/generator/ProjectGenerator.java
> +      pomBuilder.replace(idx, idx+15, resolveCustomPlugins(request, 3));
Why do you use string replace for this case? You can add a model variable (and a placeholder in pom), and process it using normal doGenerateMavenPom(model) method used (3 lines above)

2018-08-01 08:18 UTC, Igor-Ivaniuk commented on catalyst-generator/src/main/java/com/intellecteu/catalyst/generator/ProjectGenerator.java
> +            String[] namesList = PluginBinding.getPlugins(dependency.getId());
As PluginBinding gets obsolete, this resolving should be changed

2018-08-06 08:30 UTC, Igor-Ivaniuk approved these changes

2018-08-06 08:31 UTC, merged