migrate use cases to SpringBoot 2.0.1 and Camel 2.22.0
IntellectEU/catalyst-bootstrap pull request #31
Opened 2018-08-07 14:28 UTC by taras-shvyryd-intellecteu

2018-08-08 15:08 UTC, Igor-Ivaniuk requested changes

2018-08-08 15:08 UTC, Igor-Ivaniuk commented on catalyst-service/src/main/resources/application.yml
> +      id: 2.0.1.RELEASE
Currently, the latest release is **v2.0.4.RELEASE** - let's follow Spring Boot's versions

2018-08-08 15:08 UTC, Igor-Ivaniuk commented on catalyst-service/src/main/resources/application.yml
> +camel.version: 2.22.0
This should be not needed anymore, as correct Camel version will be resolved by BOM

2018-08-09 07:43 UTC, antoshka412 reviewed
Dependency with 'id: camel-test-spring' already exists
Please, remove it

2018-08-09 10:11 UTC, Igor-Ivaniuk approved these changes

2018-08-09 10:11 UTC, merged